### ISSUE TITLE
Leading Alignment

### ISSUE THREAD

**Issue by Killianoni** [ylem/swiftui-egmented-control-demo#1]
Hello nice work ! I'm using it on my project but i'd like to know how i could align the text and selector obviously at leading and chose the left padding to adjust it how i want ! Thanks for your work !

**Comment by ylem** [comment]
Hi @Killianoni, thanks for the comment. I have quick update the code to support a `leading` layout ( by setting a horizontal space  )

**Comment by Killianoni** [comment]
Yo thanks a lot that helped me so much i have a last question do you know if it's possible to position the divider under the selector like this ?
<img width="507" alt="image" src="https://user-images.githubusercontent.com/71253392/212075953-090c91f2-a4ba-4cb5-abbc-777927ea8675.png">

**Comment by ylem** [comment]
@Killianoni You can add a `ZStack` (with .bottomLeading align) and add Divider inside it.

![Screenshot 2023-01-12 at 14 52 48](https://user-images.githubusercontent.com/72552/212099089-5db254d9-3511-4633-97e7-5ed57b169e75.png)

**Comment by ylem** [comment]
![Screenshot 2023-01-12 at 14 54 56](https://user-images.githubusercontent.com/72552/212099622-64664f98-3401-4ad4-9baa-2b965978d502.png)

**Comment by ylem** [comment]
Or change the Divider to a `Rectangle()` if you want to match the design.

**Comment by Killianoni** [comment]
Insane thanks you have a good day cya !
